name: SCGeneral
author: superckl
version: 3.0
main: me.superckl.scgeneral.SCGeneral
website: www.sensationcraft.info
depend: [Factions, Lockette, PermissionsEx, Votifier, Essentials, xAuth, CombatLogger]
commands:
  shout:
    description: Shout a message
    aliases: [s]
  factioncheck:
    description: Check a factions for overlapping IPs.
  clearinvis:
    description: Clear invisibility.