name: SCGeneral
authors: [superckl, DarkSeraphim]
version: 3.1
main: org.sensationcraft.scgeneral.SCGeneral
website: www.sensationcraft.info
depend: [Factions, Lockette, Votifier, Essentials, SCLogin, mcMMO, ProtocolLib]
commands:
  shout:
    description: Shout a message
    aliases: [s]
  factioncheck:
    description: Check a factions for overlapping IPs.
  clearinvis:
    description: Clear invisibility.
  shoutmute:
    description: Toggle shout.
    aliases: [toggleshout, stfushout]
  helprequest:
    description: Request help from a staff member.
    aliases: [requesthelp, halp]
  helpread:
    description: Read a help request.
  helplist:
    description: List all the help requests.
  helpaccept:
    description: Accept a help request.
  helpcancel:
    description: Cancel your help request.
  helpdeny:
    description: Deny a help request.
  antibear:
    description: Block bear.
  killshout:
    description: Kill shout.
  tpcheck:
    description: Check the current tp request
  overrideban:
    description: Perform a permanent ban overriding the ban system.
    aliases: [oban]
  resetbans:
    description: Reset the bans for a player.
  getbans:
    description: Get the ban count for a player.
  delhomes:
    description: Deletes the homes within a certain radius of yourself.
  head:
    description: Get the head of a player.
  expel:
    description: Expel all players in a radius.
  togglepickup:
    description: Toggles whether you pickup items while vanished
  bounty:
    descrition: Place a bounty on a player.
    aliases: [assasinate, placebounty]
  checkbounties:
    decription: Check a player's bounties.
    aliases: [getbounties, bounties]
  duel:
    description: Duel a player!
    aliases: [challenge]
  spectate:
    description: Spectate a duel!
  deny:
    description: Deny a duel request.
  accept:
    description: Accept a duel request.
  cancel:
    description: Cancel your duel request.
  end:
    description: End the duel in the arena.
    aliases: [forceend]
  addons:
    description: Command for the Addon Manager :3.
  seamlessreload:
    description: Attempt to reload just a listener.
