name: SCGeneral
author: superckl
version: 3.0
main: me.superckl.scgeneral.SCGeneral
website: www.sensationcraft.info
depend: [Factions, Lockette, Votifier, Essentials, SCLogin, CombatLogger]
commands:
  shout:
    description: Shout a message
    aliases: [s]
  factioncheck:
    description: Check a factions for overlapping IPs.
  clearinvis:
    description: Clear invisibility.
  shoutmute:
    description: Toggle shout.
    aliases: [toggleshout, stfushout]
  helprequest:
    description: Request help from a staff member.
    aliases: [requesthelp]
  helpread:
    description: Read a help request.
  helplist:
    description: List all the help requests.
  helpaccept:
    description: Accept a help request.
  helpcancel:
    description: Cancel your help request.
  helpdeny:
    description: Deny a help request.
  antibear:
    description: Block bear.
  killshout:
    description: Kill shout.
  tpcheck:
    description: Check the current tp request